### ISSUE TITLE
There's a bug when Tap Try again & try again & try again

### ISSUE THREAD

**Issue by HarrisHan** [jVirus/flappy-fly-bird#2]

**Comment by eleev** [comment]
There is exactly the same issue was already opened [see](
https://github.com/jVirus/flappy-fly-bird/issues/1). Please, read the opened and closed issues more carefully. 

I appreciate your interest for the game. Thanks for you feedback, the issue will be resolved in the next update

**Comment by eleev** [comment]
If you refer to a some different issue, please write more descriptive comment. What you wrote is not going to help anyhow, it just tells that you have some hypothetical issue.

**Comment by eleev** [comment]
The fix was implemented in [1.4.5](https://github.com/jVirus/flappy-fly-bird/releases/tag/1.4.5). Please, take a look and if you face with some issue, either create a new issue or re-open this issue again. 

Thanks for you feedback and interest in this game.
